[tool.poetry]
name = "shapes_sample"
version = "0.0.1"
description = "Library of code for working with shapes. Originated from https://github.com/Lmooney25/shapes"
authors = ["maintainer <maintainer@nowhere.org>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
behave = "^1.2.6"
coverage = "~7.3.3"
junitparser = "~3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
